# Generated by Django 4.2.1 on 2023-05-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realstate", "0002_biensimmobilier_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="biensimmobilier",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
